update functinos/xs_source

diff --git a/functions/xs_source b/functions/xs_source
--- a/functions/xs_source
+++ b/functions/xs_source
@@ -6,10 +6,10 @@
 # Created: Sunday, 2026/08/09 - 17:55:06
 # Author.: @fbnmtz, (fabiano.matoz@gmail.com)
 # ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
-# Last Modified: Sunday, 2026/08/09 - 22:04:35
+# Last Modified: Monday, 2026/08/10 - 00:51:20
 # Modified By..: @fbnmtz, (fabiano.matoz@gmail.com)
 # ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
-# Version: 0.0.2.20
+# Version: 0.0.3.38
 # ~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~·~·~·~·~·~·~·~~·~·~·~·~·~~·~·~·~·~·~·~·~
 # Description: 
 #  >
@@ -17,21 +17,24 @@
 # HISTORY:
 #
 
-# def xs_source(name): function to source a script from the repository (local or using curl)
-#   ex: xs_source "init args colors functions/upcase"
+# def xs_source(filename): function to source a script from the repository (local or using curl)
+#   ex: xs_source "args system colors functions/upcase"
 function xs_source() {
+  local remote="https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master"
   # iterate over all libs/functions
-  for path in "$@"; do
-    # test if local path/file exist?
-    if [ -f "$path" ]; then
-      if ! source "../$path"; then
-        echo "xs_source() - Error sourcing local file: $path" >&2 && exit 1
+  for filename in "$@"; do
+    # test if local filename exist?
+    if [ -f "$filename" ]; then
+      if ! source "$filename" && ! source "../$filename" ; then
+        echo "xs_source() - Error sourcing local file: $filename" >&2 && exit 1
       fi
     else
       # not found? load it from web (xSHELL repo on github)
-      if ! source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/fbnmtz/xSHELL/refs/heads/master/${path})"; then
-        echo "xs_source() - Error sourcing web file: $path" >&2 && exit 1
+      if ! source /dev/stdin <<< "$(curl -s ${remote}/${filename})"; then
+        echo "xs_source() - Error sourcing web file: $filename" >&2 && exit 1
       fi
     fi
   done
 }
+
+function xsource () { xs_source "$@"; }
